config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'users/sign_up' => 'users/registrations#create'
  end
  resources :person_details
  resources :incomes
  resources :expenditures
  resources :medical_details
  resources :education_details
  resources :types
  resources :documents
  resources :categories

  root to: "person_details#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
	mount_uploader :picture ,ProfiepicUploader
end

app/models/education_detail.rb
class EducationDetail < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
end

app/models/income.rb
class Income < ActiveRecord::Base
end

app/models/medical_detail.rb
class MedicalDetail < ActiveRecord::Base
end

app/models/person_detail.rb
class PersonDetail < ActiveRecord::Base
	validates_uniqueness_of :user_id
	mount_uploader :profilepic ,ProfiepicUploader
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :sendmail

  def sendmail
  	UserMailer.send_signup_email(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	def new
		@document=Document.new
	end
	def show
		@document=Document.find(params[:id])
	end
	def create
		@document=Document.new(document_params)
		if @document.save
			redirect_to documents_path,notice: "Successully created"
		else
			render action: "new"
		end
	end
	def edit
		@document=Document.find(params[:id])
	end
	def update
		@document=Document.find(params[:id])
		if @document.update_attributes(document_params)
				redirect_to documents_path,notice: "Successully updated"
		else
			render action: "update"
		end
	end
	def destroy
		@document=Document.find(params[:id])
		if @document.delete
			redirect_to documents_path,notice: "Successully deleted"
		else
			render action: "delete"
		end
	end
	private
	def document_params
		params[:document].permit(:person_detail_id,:title,:category_id,:picture)
	end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
	def new
		@income=Income.new
	end
	def show
		@income=Income.find(params[:id])
	end
	def create
		@income=Income.new(income_params)
		if @income.save
			redirect_to person_details_path
		else
			render action: "new"
		end
	end
	def edit
		@income=Income.find(params[:id])
	end
	def update
		@income=Income.find(params[:id])
		if @income.update_attributes(income_params)
				redirect_to person_details_path
		else
			render action: "update"
		end
	end
	def destroy
		@income=Income.find(params[:id])
		if @income.delete
			redirect_to person_details_path
		else
			render action: "delete"
		end
	end
	private
	def income_params
		params[:income].permit(:person_detail_id,:type_id,:recieved_in,:amount,:date)
	end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
	def new
		@type=Type.new
	end
	def show
		@type=Type.find(params[:id])
	end
	def create
		@type=Type.new(type_params)
		if @type.save
			redirect_to types_path
		else
			render action: "new"
		end
	end
	def edit
		@type=Type.find(params[:id])
	end
	def update
		@type=Type.find(params[:id])
		if @type.update_attributes(type_params)
				redirect_to type_path
		else
			render action: "update"
		end
	end
	private
	def type_params
		params[:type].permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/education_details_helper.rb
module EducationDetailsHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/medical_details_helper.rb
module MedicalDetailsHelper
end

app/helpers/person_details_helper.rb
module PersonDetailsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/documents/edit.html.erb
<h1>Edit Document Detail</h1>
<%= form_for @document do |f|%> 
	<%if @document.errors.any? %>
		<h4>These errors prvented the form from being saved.</h4>
		<ul style="color:red">
			<% @document.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
			<%end%>
		</ul>
	<%end%>  

	<%=f.hidden_field :person_detail_id, :value => PersonDetail.find_by(user_id: current_user.id).id%>
	<%="Title : "%><%=f.text_field :title %><br />
	<%="Category  : "%><%= f.collection_select :category_id, Category.all,:id,:name%><br />
	<%=f.file_field :picture,html: {multipart: true}%>
	<%=f.submit%>
<%end%>

app/views/documents/index.html.erb
<h3>Listing all Documents</h3>
<%docs=Document.where('person_detail_id = ?',(PersonDetail.find_by(user_id: current_user.id).id))%>
<%if not(docs.empty?)%>
	<table border='1'>
		<thead>
		<tr>
			<th>Sl. No.</th>
			<th>Title</th>
			<th>Category</th>
			<th>Action</th>
		</tr>
		</thead>
		<tbody>
			<%docs.order(:category_id ).each.with_index(1) do |doc,index|%>
			<tr>
			   	<td><%=index%></td>
				<td><%=doc.title%></td>
				<td><%=Category.find(doc.category_id).name%></td>
				<td><%=link_to "Show",document_path(doc.id)%> | <%=link_to "Update",edit_document_path(doc.id)%> | <%=link_to "Delete",document_path(doc.id),:method => 'delete'%> </td>
			</tr>
			<%end%>
		</tbody>
		</table>
<h3>Total Documents - <%=docs.size%></h3>
<%else%>
	<%="No Document found"%><br />
<%end%>
<%=link_to "Create a new Docoment",new_document_path%>

app/views/documents/new.html.erb
<h1>Add Document Detail</h1>
<%= form_for @document do |f|%> 
	<%if @document.errors.any? %>
		<h4>These errors prvented the form from being saved.</h4>
		<ul style="color:red">
			<% @document.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
			<%end%>
		</ul>
	<%end%>  

	<%=f.hidden_field :person_detail_id, :value => PersonDetail.find_by(user_id: current_user.id).id%>
	<%="Title : "%><%=f.text_field :title %><br />
	<%="Category  : "%><%= f.collection_select :category_id, Category.all,:id,:name%><br />
	<%=f.file_field :picture,html: {multipart: true}%>
	<%=f.submit%>
<%end%>

app/views/documents/show.html.erb
<label>Title </label>- <%=@document.title%><br />
<label>Category</label> - <%=Category.find(@document.category_id).name%><br />
<label>Picture </label>- <%= image_tag(@document.picture.url)%><br /><%=link_to "    Back",:back%>

app/views/incomes/edit.html.erb
<h1>Edit Income Detail</h1>
<%= form_for @income do |f|%>
	<%if @income.errors.any? %>
		<h4>These erros prvented the form from being saved.</h4>
		<ul style="color:red">
			<% @income.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
			<%end%>
		</ul>
	<%end%>  

	<h4><%="Type : "%><%= f.collection_select :type_id, Type.all,:id,:name%><br />
	<%="Recieved in  : "%><%= f.select :recieved_in,options_for_select([['CASH','CASH'],['CHEQUE','CHEQUE'],['CREDIT CARD','CREDIT CARD'],['DEBIT CARD','DEBIT CARD']])%><br />
	<%="Amount : "%><%=f.text_field :amount %><br />
	<%="Date : "%><%=f.date_field :date %><br /></h4>
	<%=f.submit%>
<%end%>

app/views/incomes/index.html.erb
<b><center><h3>One Year Incomes</h3></b></center><br/>
<%incomes=Income.where('person_detail_id = ?',(PersonDetail.find_by(user_id: current_user.id).id)).where('date >=? and date<=?',Date.today.beginning_of_month - 12.month,Date.today)%>
<div class="row">
	<%currentdate=Date.today.beginning_of_month - 12.month%>
	<%while currentdate <= Date.today %>
		<%(monthlyincomes=incomes.where('date>=? and date<=?',currentdate,currentdate.end_of_month))%>
	<div class="col-md-6">
			<table border='1'>
				<thead>
					<tr>
					<th>Sl. No.</th>
					<th>Type</th>
					<th>Recieved In</th>
					<th>Amount</th>
					<th>Date</th>
					<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<%=currentdate.strftime("%B  %Y")%>
					<%monthlyincomes.order(:date ).each.with_index(1) do |income,index|%>
						<tr>
					    <td><%=index%></td>
						<td><%=Type.find(income.type_id).name%></td>
						<td><%=income.recieved_in%></td>
						<td><%=income.amount%></td>
						<td><%=income.date%></td>
						<td><%=link_to "Update",edit_income_path(income.id)%> | <%=link_to "Delete",income_path(income.id),:method => 'delete'%></td>
						</tr>
					<%end%>
					Income = <%=monthlyincomes.pluck(:amount).sum%>
					<%currentdate+=1.month%>
					<hr>
				</tbody>
			</table>
	</div>
	<div class="col-md-6">
	<%t=Hash.new%>
	<%monthlyincomes.pluck(:type_id).uniq.each do |onetype|%>
			<%t.update(Type.find(onetype).name => monthlyincomes.where('type_id=?',onetype).pluck(:amount).sum)%>
	<%end%>
	<%= pie_chart t%>
	</div>
<%end%></div>
<div class="row">
	<div class="col-md-6">
	<%types=incomes.all.pluck(:type_id).uniq%>
	<h2>Total Yearly Income = Rs <%=incomes.pluck(:amount).sum%> -/</h2>
	<%types.each do |type|%>
		<%=link_to Type.find(type).name,income_path(Income.find_by(type_id: type).id)%> : <%=incomes.where("type_id=?",type).pluck(:amount).sum%><br />
	<%end%></div>
	<div class="col-md-6">
		<%a=Hash.new%>
		<%incomes.pluck(:type_id).uniq.each do |onetype|%>
			<%a.update(Type.find(onetype).name => incomes.where('type_id=?',onetype).pluck(:amount).sum)%>
	<%end%>
	<%= pie_chart a%>
	</div>
</div>

app/views/incomes/new.html.erb
<h1>Add Income Detail</h1>
<%= form_for @income do |f|%> 
	<%if @income.errors.any? %>
		<h4>These erros prevented the form from being saved.</h4>
		<ul style="color:red">
			<% @income.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
			<%end%>
		</ul>
	<%end%>  
  
    <%=f.hidden_field :person_detail_id, :value => PersonDetail.find_by(user_id: current_user.id).id%>
	<%="Type  : "%><%= f.collection_select :type_id, Type.all,:id,:name%><br />
	<%="Recieved in  : "%><%= f.select :recieved_in,options_for_select([['CASH','CASH'],['CHEQUE','CHEQUE'],['CREDIT CARD','CREDIT CARD'],['DEBIT CARD','DEBIT CARD']])%><br />
	<%="Amount : "%><%=f.text_field :amount %><br />
	<%="Date : "%><%=f.date_field :date %><br />
	<%=f.submit%>
<%end%>

app/views/incomes/show.html.erb
<h2>Detail of all the incomes of the selected type <%=Type.find(@income.type_id).name%></h2><br />  
<table border='1'>
		<thead>
			<tr>
			<th>Recieved In</th>
			<th>Amount</th>
			<th>Date</th>
			</tr>
		</thead>
		<tbody>
		<%typeincomes=Income.where('person_detail_id=? and type_id=?',@income.person_detail_id,@income.type_id)%>
			<%typeincomes.all.each do |typeincome|%>
				<tr>
				<td><%=typeincome.recieved_in%></td>
				<td><%=typeincome.amount%></td>
				<td><%=typeincome.date%></td>
				</tr>
			<%end%>
			<%t=typeincomes.where('date >= ? and date <= ?',Date.today.beginning_of_month - 12.month,Date.today)%><br />
		</tbody>
</table>
<h3>Total income in current month :</h3><br />
	
From this type = <%=t.where('date >= ?',Date.today.beginning_of_month).pluck(:amount).sum%><br />
	
<h3>Total income in current year :</h3><br />

From this type = <%=t.where('date >= ?',Date.today - 12.month).pluck(:amount).sum%><br />