config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'users/sign_up' => 'users/registrations#create'
  end
  resources :person_details
  resources :incomes
  resources :expenditures
  resources :medical_details
  resources :education_details
  resources :types
  resources :documents
  resources :categories

  root to: "person_details#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
	mount_uploader :picture ,ProfiepicUploader
end

app/models/education_detail.rb
class EducationDetail < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
end

app/models/income.rb
class Income < ActiveRecord::Base
end

app/models/medical_detail.rb
class MedicalDetail < ActiveRecord::Base
end

app/models/person_detail.rb
class PersonDetail < ActiveRecord::Base
	validates_uniqueness_of :user_id
	mount_uploader :profilepic ,ProfiepicUploader
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :sendmail

  def sendmail
  	UserMailer.send_signup_email(self).deliver
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	def new
		@document=Document.new
	end
	def show
		@document=Document.find(params[:id])
	end
	def create
		@document=Document.new(document_params)
		if @document.save
			redirect_to documents_path,notice: "Successully created"
		else
			render action: "new"
		end
	end
	def edit
		@document=Document.find(params[:id])
	end
	def update
		@document=Document.find(params[:id])
		if @document.update_attributes(document_params)
				redirect_to documents_path,notice: "Successully updated"
		else
			render action: "update"
		end
	end
	def destroy
		@document=Document.find(params[:id])
		if @document.delete
			redirect_to documents_path,notice: "Successully deleted"
		else
			render action: "delete"
		end
	end
	private
	def document_params
		params[:document].permit(:person_detail_id,:title,:category_id,:picture)
	end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
	def new
		@income=Income.new
	end
	def show
		@income=Income.find(params[:id])
	end
	def create
		@income=Income.new(income_params)
		if @income.save
			redirect_to person_details_path
		else
			render action: "new"
		end
	end
	def edit
		@income=Income.find(params[:id])
	end
	def update
		@income=Income.find(params[:id])
		if @income.update_attributes(income_params)
				redirect_to person_details_path
		else
			render action: "update"
		end
	end
	def destroy
		@income=Income.find(params[:id])
		if @income.delete
			redirect_to person_details_path
		else
			render action: "delete"
		end
	end
	private
	def income_params
		params[:income].permit(:person_detail_id,:type_id,:recieved_in,:amount,:date)
	end
end

app/controllers/person_details_controller.rb
class PersonDetailsController < ApplicationController
	before_action :authenticate_user!
	def new
		@persondetail=PersonDetail.new
	end
	def show
		@persondetail=PersonDetail.find(params[:id])
	end
	def create
		@persondetail=PersonDetail.new(person_detail_params)
		if @persondetail.save
			redirect_to person_details_path
		else
			render action: "new"
		end
	end
	def edit
		@persondetail=PersonDetail.find(params[:id])
	end
	def update
		@persondetail=PersonDetail.find(params[:id])
		if @persondetail.update_attributes(person_detail_params)
				redirect_to person_details_path
		else
			render action: "update"
		end
	end
	private
	def person_detail_params
		params[:person_detail].permit(:name,:sex,:date_of_birth,:address,:contact_number,:country,:user_id,:profilepic)
	end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
	def new
		@type=Type.new
	end
	def show
		@type=Type.find(params[:id])
	end
	def create
		@type=Type.new(type_params)
		if @type.save
			redirect_to types_path
		else
			render action: "new"
		end
	end
	def edit
		@type=Type.find(params[:id])
	end
	def update
		@type=Type.find(params[:id])
		if @type.update_attributes(type_params)
				redirect_to type_path
		else
			render action: "update"
		end
	end
	private
	def type_params
		params[:type].permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/education_details_helper.rb
module EducationDetailsHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/medical_details_helper.rb
module MedicalDetailsHelper
end

app/helpers/person_details_helper.rb
module PersonDetailsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/person_details/edit.html.erb
<h1>Edit Person Detail</h1>
<%= form_for @persondetail do |f|%>
	<%if @persondetail.errors.any? %>
		<h4>These erros prvented the form from being saved.</h4>
		<ul style="color:red">
			<% @persondetail.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
			<%end%>
		</ul>
	<%end%>  

	<h4><%="Name : "%><%=f.text_field :name %><br />
	<%="Sex : "%><%=f.text_field :sex %><br />
	<%="Date Of Birth : "%><%=f.date_field :date_of_birth %><br />
	<%="Address : "%><%=f.text_field :address %><br />
	<%="Contact Number : "%><%=f.text_field :contact_number %><br />
	<%="Country : "%><%=f.text_field :country %><br /></h4>
	<%=f.file_field :profilepic ,html: {multipart: true}%>
	<%=f.submit%>
<%end%>

app/views/person_details/index.html.erb
<%person=PersonDetail.find_by(user_id: current_user.id)%>
<%if person.nil?%>
	<%=link_to "Create New Detail",new_person_detail_path%>
<%else%>
<div class="row">
		<div class="col-sm-2"> <%= image_tag(person.profilepic.url ,size: "168x174") %></div>
  <div class="col-sm-5">
		<h3>Personal Detail</h3>
		Name -<%=person.name%><br/>
		Sex -<%=person.sex%> <br/>
		Date of birth -<%=person.date_of_birth.strftime('%d-%B-%Y')%><br/>
		Address -<%=person.address%><br/>
		Contact Number -<%=person.contact_number%><br/>
		Country -<%=person.country%><br/>
  </div>
  <div class="col-sm-5">
	<h3>Medical Detail</h3>
	<%medical=MedicalDetail.find_by(person_detail_id: person.id)%>
		<%if medical.nil?%>
			<%=link_to "Create New Detail",new_medical_detail_path%>
		<%else%>
				Blood Group -<%=medical.blood_group%><br /> 
				Family Doctor Name -<%=medical.family_doctor_name%><br />
				Family Doctor Number -<%=medical.family_doctor_number%><br />
		<%end%>
  </div>
 </div>
	<center><h3>Education Details</h3>
	<%educationdetails=EducationDetail.where('person_detail_id=?',person.id)%>
		<%if educationdetails.empty?%>
			<%=link_to "Create Education Detail",new_education_detail_path%>
		<%else%>
			<table border='1'>
				<thead>
					<tr>
					<th>Sl No.</th>
					<th><center>Institution</center></th>
					<th><center>Board/University</center></th>
					<th><center>Percentage/CGPA</center></th>
					<th><center>Year</center></th>
					<th><center>Certificate Title</center></th>
					<th><center>Action</center></th>
					</tr>
				</thead>
				<tbody>
					<%educationdetails.each.with_index(1) do |educationdetail,index|%>
						<tr>
					    <td><center><%=index%></center></td>
						<td><center><%=educationdetail.institution_name%></center></td>
						<td><center><%=educationdetail.board_or_university_name%></center></td>
						<td><center><%=educationdetail.percentage_or_cgpa%></center></td>
						<td><center><%=educationdetail.year_of_passing%></center></td>
						<td><center><%=educationdetail.certificate_type_name%></center></td>
						<td><center><%=link_to "Update",edit_education_detail_path(educationdetail.id)%> | <%=link_to "Delete",education_detail_path(educationdetail.id),:method => 'delete' %></center></td>
						</tr>
					<%end%>
				</tbody>
			</table>
		<%end%><br />
		<h3>Transactions in current month</h3>
		</center>
<div class="row">
  <div class="col-sm-6">
		<h3>Incomes</h3>
		<%incomes=Income.where('person_detail_id=?',person.id).where('date >=? and date<=?',Date.today.beginning_of_month,Date.today.end_of_month)%>
		<%if incomes.empty?%>
			<%="No record found"%> 
		<%else%>
			<table border='1'>
			<thead>
				<tr>
				<th><center>Sl. No.</center></th>
				<th><center>Type</center></th>
				<th><center>Recieved In</center></th>
				<th><center>Amount</center></th>
				<th><center>Date</center></th>
				<th><center>Action</center></th>
				</tr>
			</thead>
			<tbody>
				<%incomes.each.with_index(1) do |income,index|%>
					<tr>
			    	<td><center><%=index%></center></td>
					<td><center><%=Type.find(income.type_id).name%></center></td>
					<td><center><%=income.recieved_in%></center></td>
					<td><center><%=income.amount%></center></td>
					<td><center><%=income.date%></center></td>
					<td><center><%=link_to "Update",edit_income_path(income.id)%> | <%=link_to "Delete",income_path(income.id),:method => 'delete'%></center></td>
					</tr>
				<%end%>
			</tbody>
			</table>
  			<h3>Total income : <%=incomes.pluck(:amount).sum%></h3>
		<%end%>
		<%=link_to "View all incomes",incomes_path%><br />
  </div>
  <div class="col-sm-6">
		<h3>Expenses</h3>
		<%expenditures=Expenditure.where('person_detail_id=?',person.id).where('date >=? and date<=?',Date.today.beginning_of_month,Date.today.end_of_month)%>
		<%if expenditures.empty?%>
			<%="No record found."%> 
		<%else%>
			<table border='1'>
				<thead>
					<tr>
					<th><center>Sl No.</center></th>
					<th><center>Type</center></th>
					<th><center>Payment Method</center></th>
					<th><center>Amount</center></th>
					<th><center>Date</center></th>
					<th><center>Action</center></th>
					</tr>
				</thead>
				<tbody>
					<%expenditures.each.with_index(1) do |expenditure,index|%>
						<tr>
					    <td><center><%=index%></center></td>
						<td><center><%=Type.find(expenditure.type_id).name%></center></td>
						<td><center><%=expenditure.payment_method%></center></td>
						<td><center><%=expenditure.amount%></center></td>
						<td><center><%=expenditure.date%></center></td>
						<td><center><%=link_to "Update",edit_expenditure_path(expenditure.id)%> | <%=link_to "Delete",expenditure_path(expenditure.id),:method => 'delete'%></center></td>
						</tr>
					<%end%>
				</tbody>
			</table>
			<h3>Total expenditure : <%=expenditures.pluck(:amount).sum%></h3>
		<%end%>
		<%=link_to "View all expenditure",expenditures_path%>
  </div>
<%end%>

app/views/person_details/new.html.erb
<h1>Add Person Detail</h1>
<%= form_for @persondetail do |f|%>
	<%if @persondetail.errors.any? %>
		<h4>These errors prvented the form from being saved.</h4>
		<ul style="color:red">
			<% @persondetail.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
			<%end%>
		</ul>
	<%end%>  

	<h4><%="Name : "%><%=f.text_field :name %><br />
	<%="Sex : "%><%=f.text_field :sex %><br />
	<%="Date Of Birth : "%><%=f.date_field :date_of_birth %><br />
	<%="Address : "%><%=f.text_field :address %><br />
	<%="Contact Number : "%><%=f.text_field :contact_number %><br />
	<%="Country : "%><%=f.text_field :country %><br />
	<%=f.file_field :profilepic,html: {multipart: true}%>
	<%=f.hidden_field :user_id, :value => current_user.id %><br /></h4>
	<%=f.submit%>
<%end%>

app/views/person_details/show.html.erb
<h2>Detail about the person</h2><br />  
<table border='1'>
		<thead>
			<tr>
			<th>Name</th>
			<th>Sex</th>
			<th>Date of birth</th>
			<th>Address</th>
			<th>Contact Number</th>
			<th>Country</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%=@persondetail.name%></td>
				<td><%=@persondetail.sex%></td>
				<td><%=@persondetail.date_of_birth%></td>
				<td><%=@persondetail.address%></td>
				<td><%=@persondetail.contact_number%></td>
				<td><%=@persondetail.country%></td>
			</tr>
		</tbody>
</table>
<%=link_to "Update detail",edit_person_detail_path(@persondetail.id)%> <br /><br />