config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'users/sign_up' => 'users/registrations#create'
  end
  resources :person_details
  resources :incomes
  resources :expenditures
  resources :medical_details
  resources :education_details
  resources :types
  resources :documents
  resources :categories

  root to: "person_details#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
	mount_uploader :picture ,ProfiepicUploader
end

app/models/education_detail.rb
class EducationDetail < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
end

app/models/income.rb
class Income < ActiveRecord::Base
end

app/models/medical_detail.rb
class MedicalDetail < ActiveRecord::Base
end

app/models/person_detail.rb
class PersonDetail < ActiveRecord::Base
	validates_uniqueness_of :user_id
	mount_uploader :profilepic ,ProfiepicUploader
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :sendmail

  def sendmail
  	UserMailer.send_signup_email(self).deliver
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	def new
		@document=Document.new
	end
	def show
		@document=Document.find(params[:id])
	end
	def create
		@document=Document.new(document_params)
		if @document.save
			redirect_to documents_path,notice: "Successully created"
		else
			render action: "new"
		end
	end
	def edit
		@document=Document.find(params[:id])
	end
	def update
		@document=Document.find(params[:id])
		if @document.update_attributes(document_params)
				redirect_to documents_path,notice: "Successully updated"
		else
			render action: "update"
		end
	end
	def destroy
		@document=Document.find(params[:id])
		if @document.delete
			redirect_to documents_path,notice: "Successully deleted"
		else
			render action: "delete"
		end
	end
	private
	def document_params
		params[:document].permit(:person_detail_id,:title,:category_id,:picture)
	end
end

app/controllers/education_details_controller.rb
class EducationDetailsController < ApplicationController
	def new
		@educationdetail=EducationDetail.new
	end
	def show
		@educationdetail=EducationDetail.find(params[:id])
	end
	def create
		@educationdetail=EducationDetail.new(education_detail_params)
		if @educationdetail.save
			redirect_to person_details_path
		else
			render action: "new"
		end
	end
	def edit
		@educationdetail=EducationDetail.find(params[:id])
	end
	def update
		@educationdetail=EducationDetail.find(params[:id])
		if @educationdetail.update_attributes(education_detail_params)
				redirect_to person_details_path
		else
			render action: "update"
		end
	end
	def destroy
		@educationdetail=EducationDetail.find(params[:id])
		if @educationdetail.delete
			redirect_to person_details_path
		else
			render action: "delete"
		end
	end
	private
	def education_detail_params
		params[:education_detail].permit(:person_detail_id,:institution_name,:board_or_university_name,:percentage_or_cgpa,:year_of_passing,:certificate_type_name)
	end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
	def new
		@income=Income.new
	end
	def show
		@income=Income.find(params[:id])
	end
	def create
		@income=Income.new(income_params)
		if @income.save
			redirect_to person_details_path
		else
			render action: "new"
		end
	end
	def edit
		@income=Income.find(params[:id])
	end
	def update
		@income=Income.find(params[:id])
		if @income.update_attributes(income_params)
				redirect_to person_details_path
		else
			render action: "update"
		end
	end
	def destroy
		@income=Income.find(params[:id])
		if @income.delete
			redirect_to person_details_path
		else
			render action: "delete"
		end
	end
	private
	def income_params
		params[:income].permit(:person_detail_id,:type_id,:recieved_in,:amount,:date)
	end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
	def new
		@type=Type.new
	end
	def show
		@type=Type.find(params[:id])
	end
	def create
		@type=Type.new(type_params)
		if @type.save
			redirect_to types_path
		else
			render action: "new"
		end
	end
	def edit
		@type=Type.find(params[:id])
	end
	def update
		@type=Type.find(params[:id])
		if @type.update_attributes(type_params)
				redirect_to type_path
		else
			render action: "update"
		end
	end
	private
	def type_params
		params[:type].permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/education_details_helper.rb
module EducationDetailsHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/medical_details_helper.rb
module MedicalDetailsHelper
end

app/helpers/person_details_helper.rb
module PersonDetailsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/education_details/edit.html.erb
<h1>Edit Education Detail</h1>
<%= form_for @educationdetail do |f|%>
	<%if @educationdetail.errors.any? %>
		<h4>These erros prvented the form from being saved.</h4>
		<ul style="color:red">
			<% @educationdetail.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
			<%end%>
		</ul>
	<%end%>  

	<h4>
	<%="Institution Name : "%><%=f.text_field :institution_name %><br />
	<%="Certificate : "%><%=f.text_field :certificate_type_name %><br />
	<%="Board/University : "%><%=f.text_field :board_or_university_name %><br />
	<%="Percentage/CGPA : "%><%=f.text_field :percentage_or_cgpa %><br />
	<%="Year Of Passing: "%><%=f.text_field :year_of_passing %><br /></h4>
	<%=f.submit%>
<%end%>

app/views/education_details/index.html.erb
<%=link_to "Create new detail",new_education_detail_path%> 
<h3>Listing all Education details in database</h3>
<%educationdetails=EducationDetail.all%>
<%if educationdetails.empty?%>
	<%="Empty database."%>
<%else%>
	<table border='1'>
		<thead>
			<tr>
			<th>Sl No.</th>
			<th>Person Name</th>
			<th>Institution</th>
			<th>Board/University</th>
			<th>Percentage/CGPA</th>
			<th>Year</th>
			<th>Certificate Title</th>
			</tr>
		</thead>
		<tbody>
			<%educationdetails.each.with_index(1) do |educationdetail,index|%>
				<tr>
			    <td><%=index%></td>
				<td><%=link_to PersonDetail.find(educationdetail.person_detail_id).name,person_detail_path(educationdetail.person_detail_id)%></td>
				<td><%=educationdetail.institution_name%></td>
				<td><%=educationdetail.board_or_university_name%></td>
				<td><%=educationdetail.percentage_or_cgpa%></td>
				<td><%=educationdetail.year_of_passing%></td>
				<td><%=educationdetail.certificate_type_name%></td>
				</tr>
			<%end%>
		</tbody>
	</table>
<%end%>

app/views/education_details/new.html.erb
<h1>Add Education Detail</h1>
<%= form_for @educationdetail do |f|%> 
	<%if @educationdetail.errors.any? %>
		<h4>These erros prevented the form from being saved.</h4>
		<ul style="color:red">
			<% @educationdetail.errors.full_messages.each do |msg| %>
				<li><%=msg %></li>
			<%end%>
		</ul>
	<%end%>  

	<%="Institution Name : "%><%=f.text_field :institution_name%><br />
	<%="Certificate : "%><%=f.text_field :certificate_type_name %><br />
	<%="Board/University name : "%><%=f.text_field :board_or_university_name %><br />
	<%="Percentage/CGPA : "%><%=f.text_field :percentage_or_cgpa %><br />
	<%="Year : "%><%=f.text_field :year_of_passing %><br />
	<%=f.hidden_field :person_detail_id, :value => PersonDetail.find_by(user_id: current_user.id).id%><br /><br />
	<%=f.submit%>
<%end%>

app/views/education_details/show.html.erb
<h2>Detail about the Education</h2><br />  
<table border='1'>
		<thead>
			<tr>
			<th>Name</th>
			<th>Institution Name</th>
			<th>Certificate Title</th>
			<th>Board or University</th>
			<th>Percentage / CGPA</th>
			<th>Year</th>
			</tr>
		</thead>
		<tbody>
			<tr>
			    <td><%=PersonDetail.find(@educationdetail.person_detail_id).name%></td>
				<td><%=@educationdetail.institution_name%></td>
				<td><%=@educationdetail.certificate_type_name%></td>
				<td><%=@educationdetail.board_or_university_name%></td>
				<td><%=@educationdetail.percentage_or_cgpa%></td>
				<td><%=@educationdetail.year_of_passing%></td>
			</tr>
		</tbody>
</table>
<%=link_to "Update detail",edit_education_detail_path(@educationdetail.id)%> 