config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get 'users/sign_up' => 'users/registrations#create'
  end
  resources :person_details
  resources :incomes
  resources :expenditures
  resources :medical_details
  resources :education_details
  resources :types
  resources :documents
  resources :categories

  root to: "person_details#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base
	mount_uploader :picture ,ProfiepicUploader
end

app/models/education_detail.rb
class EducationDetail < ActiveRecord::Base
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
end

app/models/income.rb
class Income < ActiveRecord::Base
end

app/models/medical_detail.rb
class MedicalDetail < ActiveRecord::Base
end

app/models/person_detail.rb
class PersonDetail < ActiveRecord::Base
	validates_uniqueness_of :user_id
	mount_uploader :profilepic ,ProfiepicUploader
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :sendmail

  def sendmail
  	UserMailer.send_signup_email(self).deliver
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	def new
		@document=Document.new
	end
	def show
		@document=Document.find(params[:id])
	end
	def create
		@document=Document.new(document_params)
		if @document.save
			redirect_to documents_path,notice: "Successully created"
		else
			render action: "new"
		end
	end
	def edit
		@document=Document.find(params[:id])
	end
	def update
		@document=Document.find(params[:id])
		if @document.update_attributes(document_params)
				redirect_to documents_path,notice: "Successully updated"
		else
			render action: "update"
		end
	end
	def destroy
		@document=Document.find(params[:id])
		if @document.delete
			redirect_to documents_path,notice: "Successully deleted"
		else
			render action: "delete"
		end
	end
	private
	def document_params
		params[:document].permit(:person_detail_id,:title,:category_id,:picture)
	end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
	def new
		@income=Income.new
	end
	def show
		@income=Income.find(params[:id])
	end
	def create
		@income=Income.new(income_params)
		if @income.save
			redirect_to person_details_path
		else
			render action: "new"
		end
	end
	def edit
		@income=Income.find(params[:id])
	end
	def update
		@income=Income.find(params[:id])
		if @income.update_attributes(income_params)
				redirect_to person_details_path
		else
			render action: "update"
		end
	end
	def destroy
		@income=Income.find(params[:id])
		if @income.delete
			redirect_to person_details_path
		else
			render action: "delete"
		end
	end
	private
	def income_params
		params[:income].permit(:person_detail_id,:type_id,:recieved_in,:amount,:date)
	end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
	def new
		@type=Type.new
	end
	def show
		@type=Type.find(params[:id])
	end
	def create
		@type=Type.new(type_params)
		if @type.save
			redirect_to types_path
		else
			render action: "new"
		end
	end
	def edit
		@type=Type.find(params[:id])
	end
	def update
		@type=Type.find(params[:id])
		if @type.update_attributes(type_params)
				redirect_to type_path
		else
			render action: "update"
		end
	end
	private
	def type_params
		params[:type].permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/helpers/medical_details_helper.rb
module MedicalDetailsHelper
end

app/helpers/person_details_helper.rb
module PersonDetailsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-inverse">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <h3><%=link_to "DigitalLife",person_details_path%></h3>
  </div>
  
  <div class="collapse navbar-collapse js-navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Update/Create <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          <%if (personexists=PersonDetail.find_by(user_id: current_user.id))%>
            <li><%= link_to "Update Basic Profile", edit_person_detail_path(personexists.id) %></li>
            <%if (medicalexists=MedicalDetail.find_by(person_detail_id: personexists.id))%>
              <li><%= link_to "Update Medical detail", edit_medical_detail_path(personexists.id) %></li>
              <li><%= link_to "Add Education detail", new_education_detail_path %></li>
              <li><%= link_to "Add Income detail", new_income_path%></li>
              <li><%= link_to "Add Expense detail", new_expenditure_path %></li>
            <%else%>
              <li><%= link_to "Create Medical detail", new_medical_detail_path%></li>
              <li><%= link_to "Add Education detail", new_education_detail_path %></li>
              <li><%= link_to "Add Income detail", new_income_path%></li>
              <li><%= link_to "Add Expense detail", new_expenditure_path %></li>
            <%end%>
            <li><%= link_to "My Documents", documents_path%></li>
          <%else%>
            <li><%= link_to "Create Person detail", new_person_detail_path%></li>
          <%end%>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">My account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Change your password", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path,:method => "delete" %></li>
          </ul>
        </li>
      </ul>
  </div><!-- /.nav-collapse -->
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finalproject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<%= javascript_include_tag "https://www.google.com/jsapi" %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
  <%if user_signed_in?%>
        <%= render 'layouts/navbar.html.erb'%>
  <%end%>
</head>
<body>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
	<%= yield %>
</div>
</body>
</html>